### ISSUE TITLE
Sparse Jacobian is not treated as sparse

### ISSUE THREAD

**Issue by mcr222** [numerical-mathematics/extrapolation#38]
The code must use:  methodargs["Isparse"] = scipy.sparse.identity(len(y0), dtype=float).

Because if Isparse is not sparse then Isparse+J00 (being J00 sparse) is not sparse and the problem is solved as a nonsparse problem.

**Comment by mcr222** [comment]
PS: it's an easy solve, I am just not working with the latest update (to avoid the refactoring)

**Comment by ketch** [comment]
In the current code, you don't need to do anything manually.  The code calls your Jacobian function once at the start and checks if the return value is sparse.  If it is, then a sparse identity matrix is used.

**Comment by mcr222** [comment]
Yes, but the Isparse matrix is not sparse, what's currently on the code: methodargs["Isparse"] = np.identity(len(y0), dtype=float)

**Comment by ketch** [comment]
Wow, either you or @HumamAlwassel must have done a push --force and completely clobbered a lot of the code!  No more pushing to master.  It will take me some work to sort this out.  From now on, pull request only, and only I will merge.

**Comment by ketch** [comment]
(the code you are seeing is old code resulting from that push --force)
